---
- name: ping-playbook
  hosts: Slave_Master
  become: yes
  tasks:
    - name: Learning ping module
      ping:
    - name: Install docker
      shell: "sudo amazon-linux-extras install docker=latest -y"
    - name: Install apache
      yum: 
        name: httpd
        state: latest
        update_cache: yes