---
- name: ping-playbook
  hosts: slave-node
  tasks:
- name: Learning ping module
  ping:

- name: Install Docker, Install apache
  yum:
    name: httpd
    state: installed

- name: Enabling httpd service and start the service
  service:  
    name: httpd
    enabled: yes
    state: started

- name: copying your php file in the /var/www/html
  copy: 
    src: /etc/ansible/index.php
    dest: /var/www/html/index.php
    force: yes
  
  notify:
      - name: restart httpd service

